----------------------- auto generate code --------------------------
local base = UITabView
---@class TestTabUIBase:UITabView
local TestTabUIBase = BaseClass("TestTabUIBase", base)

function TestTabUIBase:ctor(container)
	self.img_Root = self:AddImage(container.img_Root)
	self.btn_close = self:AddButton(container.btn_close)
	self.text_title = self:AddText(container.text_title)
	self.img_titleIcon = self:AddImage(container.img_titleIcon)
	self.btn_help = self:AddButton(container.btn_help)
	self.widget_tab01 = self:AddWidget(container.widget_tab01)
	self.btn_unselect01 = self:AddButton(container.btn_unselect01)
	self.img_unselect01 = self:AddImage(container.img_unselect01)
	self.text_unselect01 = self:AddText(container.text_unselect01)
	self.widget_select01 = self:AddWidget(container.widget_select01)
	self.img_select01 = self:AddImage(container.img_select01)
	self.text_select01 = self:AddText(container.text_select01)
	self.widget_tab02 = self:AddWidget(container.widget_tab02)
	self.btn_unselect02 = self:AddButton(container.btn_unselect02)
	self.img_unselect02 = self:AddImage(container.img_unselect02)
	self.text_unselect02 = self:AddText(container.text_unselect02)
	self.widget_select02 = self:AddWidget(container.widget_select02)
	self.img_select02 = self:AddImage(container.img_select02)
	self.text_select02 = self:AddText(container.text_select02)
	self.widget_tab03 = self:AddWidget(container.widget_tab03)
	self.btn_unselect03 = self:AddButton(container.btn_unselect03)
	self.img_unselect03 = self:AddImage(container.img_unselect03)
	self.text_unselect03 = self:AddText(container.text_unselect03)
	self.widget_select03 = self:AddWidget(container.widget_select03)
	self.img_select03 = self:AddImage(container.img_select03)
	self.text_select03 = self:AddText(container.text_select03)
	self.widget_tab04 = self:AddWidget(container.widget_tab04)
	self.btn_unselect04 = self:AddButton(container.btn_unselect04)
	self.img_unselect04 = self:AddImage(container.img_unselect04)
	self.text_unselect04 = self:AddText(container.text_unselect04)
	self.widget_select04 = self:AddWidget(container.widget_select04)
	self.img_select04 = self:AddImage(container.img_select04)
	self.text_select04 = self:AddText(container.text_select04)
	self.widget_tab05 = self:AddWidget(container.widget_tab05)
	self.btn_unselect05 = self:AddButton(container.btn_unselect05)
	self.img_unselect05 = self:AddImage(container.img_unselect05)
	self.text_unselect05 = self:AddText(container.text_unselect05)
	self.widget_select05 = self:AddWidget(container.widget_select05)
	self.img_select05 = self:AddImage(container.img_select05)
	self.text_select05 = self:AddText(container.text_select05)
	self.item_TabA = container.item_TabA
	self.item_TabB = container.item_TabB
end

return TestTabUIBase
