local ComonItem = {
	[1] = {
		Quality = 1,
		Type = 1,
		Effect = 1,
		CanSell = 0,
		SellValue = 0,
		Expire = 0,
		Isbroadcast = 0,
		Broadcastid = 0,
	},
	[2] = {
		Quality = 1,
		Type = 2,
		Effect = 1,
		CanSell = 0,
		SellValue = 0,
		Expire = 0,
		Isbroadcast = 0,
		Broadcastid = 0,
	},
	[3] = {
		Quality = 1,
		Type = 3,
		Effect = 1,
		CanSell = 0,
		SellValue = 0,
		Expire = 0,
		Isbroadcast = 0,
		Broadcastid = 0,
	},
	[1001] = {
		Quality = 2,
		Type = 1,
		Effect = 10000,
		CanSell = 0,
		SellValue = 0,
		Expire = 0,
		Isbroadcast = 0,
		Broadcastid = 0,
	},
	[1002] = {
		Quality = 3,
		Type = 2,
		Effect = 10000,
		CanSell = 0,
		SellValue = 0,
		Expire = 0,
		Isbroadcast = 0,
		Broadcastid = 0,
	},
	[1003] = {
		Quality = 4,
		Type = 3,
		Effect = 10000,
		CanSell = 0,
		SellValue = 0,
		Expire = 0,
		Isbroadcast = 0,
		Broadcastid = 0,
	},
}
 return ComonItem