---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
local base = require "Framework.Scene.BaseScene"
local BattleScene = BaseClass("BattleScene", base)

function BattleScene:OnCreate()

end

--预加载资源
function BattleScene:OnPrepare(...)
    logError(...)
    UIManager:LoadView(UIConfig.BattleUI)

end

function BattleScene:OnEnter()
    print("enterbattle")
end

function BattleScene:OnLeave()

end

return BattleScene