---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
local base = require "Framework.Scene.BaseScene"
local HomeScene = BaseClass("HomeScene", base)

function HomeScene:OnCreate()
    
end

--预加载资源
function HomeScene:OnPrepare(co)

end

function HomeScene:OnEnter(co)

    print("enter home")

end

function HomeScene:OnLeave()

end

return HomeScene