---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
local base = require "Framework.Scene.BaseScene"
local LoginScene = BaseClass("LoginScene", base)

function LoginScene:OnCreate()

end

--预加载资源
function LoginScene:OnPrepare()
    UIManager:LoadView(UIConfig.LoginUI)

    return true
end

function LoginScene:OnEnter()
    --打开登录界面

end

function LoginScene:OnLeave()

end

return LoginScene