---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
local base = require "Framework.Scene.BaseScene"
local LoginScene = BaseClass("LoginScene", base)

function LoginScene:OnCreate()

end

--预加载资源
function LoginScene:OnPrepare(co)
    UIManager:LoadView(UIConfig.LoginUI)
    coroutine.waituntil(co,function () return UIManager:IsViewOpen(UIConfig.LoginUI) end)
end

function LoginScene:OnEnter(co)
    --打开登录界面
    
end

function LoginScene:OnLeave()

end

return LoginScene