---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
local base = require "Framework/Scene/BaseScene"
local MainScene = BaseClass("MainScene", base)
---------------------------------------------------------------
local world_conig = require "Logic/Config/World"

function MainScene:OnCreate()

end

function MainScene:OnPrepare()
    local args = NetworkManager:SendRequest(NetMsgId.req_enter_game)
    if not args.ok then
        logError("进入游戏失败")
        return false
    end

    local sceneId = RoleModel.RoleData.sceneId
    local sceneName = world_conig[sceneId].Resource
    coroutine.Do(MapManager.LoadMap, nil, sceneName)
    AOIController:CreateEntities(args.aoi_map)
    UIManager:LoadView(UIConfig.MainUI)
    return true
end

function MainScene:OnEnter()


end

function MainScene:OnLeave()
    MapManager.Cleanup()
    EntityBehaviorManager.Cleanup()
end

return MainScene