---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
local base = require "Framework.Scene.BaseScene"
local MainScene = BaseClass("MainScene", base)

function MainScene:OnCreate()

end

function MainScene:OnPrepare(map_id)

    MapManager.LoadMap("Demo_1", nil)
    --UIManager:LoadView(UIConfig.HomeUI)
    --UIManager:LoadView(UIConfig.BattleUI)
end

function MainScene:OnEnter()


end

function MainScene:OnLeave()
    MapManager.Cleanup()
end

return MainScene