---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43

SceneConfig = {
    -- 启动场景
    LaunchScene = {
        Name = "LaunchScene",
        Type = nil,
    },
    -- 加载场景
    LoadingScene = {
        Name = "LoadingScene",
        Type = nil
    },
    -- 登陆场景
    LoginScene = {
        Name = "LoginScene",
        Type = require "Framework.Scene.LoginScene"
    },
    -- 主页场景
    HomeScene = {
        Name = "HomeScene",
        Type = require "Framework.Scene.HomeScene"
    },
    -- 战斗场景
    BattleScene = {
        Name = "BattleScene",
        Type = require "Framework.Scene.BattleScene"
    },
}