---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43

SceneConfig = {
    -- 启动场景
    LaunchScene = {
        Name = "LaunchScene",
        Type = nil,
    },
    -- 加载场景
    LoadingScene = {
        Name = "LoadingScene",
        Type = nil
    },
    -- 登陆场景
    LoginScene = {
        Name = "LoginScene",
        Type = require "Framework.Scene.LoginScene"
    },
    -- 主页场景
    MainScene = {
        Name = "Demo_1",
        Type = require "Framework.Scene.MainScene"
    },
}