--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by shenyi.
--- DateTime: 2020/3/20 15:43
require "Framework.Scene.SceneConfig"
---@class SceneManager:Updatable
local SceneManager = BaseClass("SceneManager", Updatable)
local loadManager = LoadManager

local MainCameraPath = "MainCamera"

-- 构造函数
function SceneManager:ctor()
	--@private
	---@type BaseScene
	self.current_scene = nil
	self.current_config = SceneConfig.LaunchScene
	self.scenes = {}
	self.camera_go = CS.UnityEngine.GameObject.Find(MainCameraPath)
	--logError(self.camera_go.name)
end

-- 切换场景
function SceneManager:SwitchScene(scene_config)
	if self.current_scene then
		self.current_scene:Leave()
	end

    coroutine.start(function (co)
        UIManager:UnLoadAllView(true)
        UIManager:LoadView(UIConfig.LoadingUI)
        coroutine.waituntil(co, function () return UIManager:IsViewOpen(UIConfig.LoadingUI) end)
        ---先跳空场景
        loadManager.Load(SceneConfig.LoadingScene.Name, function ()
            local sceneName = scene_config.Name
            if not self.scenes[sceneName] then
                self.scenes[sceneName] = scene_config.Type.New()
            end
            self.current_scene = self.scenes[sceneName]
            ---再跳目标场景
            loadManager.Load(sceneName, function ()
                self.current_config = scene_config
                ---此时co已经回收，必须重新开始协程
                coroutine.start(function (co2)
                    self.current_scene:Prepare(co2)
                    UIManager:UnLoadView(UIConfig.LoadingUI)
                    coroutine.waitforframes(co2, 1)
                    self.current_scene:Enter(co2)
                end)
            end)
        end, function (progress)
            self:Broadcast(EventNames.Scene.LoadProcess, progress)
        end)
    end)
end

-- 析构函数
function SceneManager:dtor()
	for _, scene in pairs(self.scenes) do
		scene:Delete()
	end
end

return SceneManager